### PR TITLE
chore: set userAgent to `go-waku`

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Comment by alrevuelta** [comment]
Great stuff! Didn't mean to be picky with "Go Waku v2 node" vs "go-waku", had no idea that you were already providing a userAgent different from the default one (was not the case in nwaku)

Thanks!

**Comment by alrevuelta** [comment]
Can we add a cli flag to configure it? In case someone doesn't want to reveal the client?

**Comment by richard-ramos** [comment]
> Can we add a cli flag to configure it? In case someone doesn't want to reveal the client?

Sure! will keep the PR open in the meantime, and once we have a name for the flag, will update it to include it.
Thank you!

**Comment by alrevuelta** [comment]
> Sure! will keep the PR open in the meantime, and once we have a name for the flag, will update it to include it.

Sure, I had in mind `agent-string` on nwaku side, to follow nimbus pattern. But no strong opinion on its name.

**Pull request merged**
